name: solid_auth
description: Authentication library to connect to a Solid server from solidproject.org
version: 0.1.13
homepage: https://github.com/anusii/solid_auth

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.0
  convert: ^3.0.1
  collection: ^1.15.0
  crypto: ^3.0.1
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  fast_rsa: ^3.0.3
  http: ^1.1.0
  intl: ^0.18.0
  jose: ^0.3.2
  jwt_decoder: ^2.0.1
  loading_indicator: ^3.1.1
  logging: ^1.0.2
  openidconnect_platform_interface: ^1.0.3
  openidconnect_web: ^1.0.21
  pointycastle: ^3.5.0
  package_info_plus: ^5.0.1
  rdflib: ^0.2.8
  url_launcher: ^6.1.12
  url_launcher_android: ^6.0.36
  uuid: ^3.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  url_launcher_android: "<=6.0.32"

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
